name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR, Build Docker Image, Tag, and Push
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 058264124336.dkr.ecr.ap-south-1.amazonaws.com
        docker build -t django .
        docker tag django:latest 058264124336.dkr.ecr.ap-south-1.amazonaws.com/django:latest
        docker push 058264124336.dkr.ecr.ap-south-1.amazonaws.com/django:latest
