name: Backend Builds
run-name: Triggered build for:- ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/**' 
      - 'libs/**'

jobs:
  DeployDev:
    name: Django
    runs-on: ubuntu-latest
    concurrency:
      group: ci-cd-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python 3.8 manually via pyenv
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
            libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
            xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

          curl https://pyenv.run | bash

          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV

          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"

          pyenv install 3.8.10
          pyenv global 3.8.10
          python --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR, Build Image, Tag, and Push
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 058264124336.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t django .
          docker tag django:latest 058264124336.dkr.ecr.ap-south-1.amazonaws.com/django:latest
          docker push 058264124336.dkr.ecr.ap-south-1.amazonaws.com/django:latest
