name: Backend Builds
run-name: Triggered build for:- ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'

jobs:
  DeployDev:
    name: Django
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR, Build Image, Tag, and Push
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 058264124336.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t django .
          docker tag django:latest 058264124336.dkr.ecr.ap-south-1.amazonaws.com/django:latest
          docker push 058264124336.dkr.ecr.ap-south-1.amazonaws.com/django:latest
